# SPDX-FileCopyrightText: 2025 Jaga Tranvo
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "superseedr"
version = "0.9.0"
edition = "2021"

[dev-dependencies]
tempfile = "3.10.1"

[dependencies]
linked-hash-map = "0.5.6"
percent-encoding = "2.3.1"
reqwest = "0.12.8"
sha1 = "0.10.6"
tokio = { version = "1", features = ["full"] }
console-subscriber = "0.1"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
magnet-url = "3.0.0"
mainline = "6.0.0"
tokio-stream = { version = "0.1.17", features = ["sync"] }
data-encoding = "2.9.0"
bendy = { version = "0.4.0", features = ["serde"] }
urlencoding = "2.1.3"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
arboard = "3.4.0"
rand = "0.8"
directories = "5.0"
toml = "0.8"
hex = "0.4"
lazy_static = "1.5.0"
sysinfo = "0.37.0"
tracing-appender = "0.2" 
ratatui-explorer = "0.2.0" 
strum = "0.27.2"
strum_macros = "0.26"
figment = { version = "0.10", features = ["toml", "env"] }
ratatui-textarea = "0.4.0"
notify = { version = "6.1.1", features = ["serde"] }
notify-debouncer-full = "0.3.1"
clap = { version = "4.5.4", features = ["derive"] }
fs2 = "0.4.3"
rlimit = "0.10"
