[package]
name = "superseedr-web"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4.44"
ratatui = { version = "=0.30.2", default-features = false, features = ["layout-cache", "std", "underline-color"] }
superseedr = { path = "../..", default-features = false, features = ["dht", "pex"] }
wasm-bindgen = "=0.2.104"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "=0.4.54"

[dev-dependencies]
wasm-bindgen-test = "=0.3.54"
