name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: superseedr

jobs:
  build_linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose

  bundle_macos:
      name: Bundle macOS App
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v5

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Create Contents directory
        run: mkdir -p "target/release/bundle/macos/${{ env.APP_NAME }}.app/Contents"

      - name: Copy Info.plist
        run: cp path/to/your/Info.plist "target/release/bundle/macos/${{ env.APP_NAME }}.app/Contents/Info.plist"

      - name: Build and Bundle macOS Application
        run: cargo bundle --target ${{ matrix.target }} # Build for the specific target

      - name: Install create-dmg
        run: brew install create-dmg
      - name: Create DMG
        run: |
          dmg_name="${{ env.APP_NAME }}-${{ github.ref_name }}-macos-${{ matrix.arch }}.dmg"
          create-dmg \
            --volname "${{ env.APP_NAME }} ${{ github.ref_name }}" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "${{ env.APP_NAME }}.app" 200 190 \
            --hide-extension "${{ env.APP_NAME }}.app" \
            --app-drop-link 600 185 \
            "target/release/${dmg_name}" \
            "target/release/bundle/macos/"

      - name: Upload macOS App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: superseedr-macos-${{ matrix.arch }}-${{ github.ref_name }} # e.g., superseedr-macos-x86_64-v1.0.0
          path: target/release/*.dmg

      strategy:
        matrix:
          include:
            - target: x86_64-apple-darwin
              arch: x86_64
            - target: aarch64-apple-darwin
              arch: aarch64
